name: Alliser - Check file types

on: [pull_request]

jobs:
  alliser:
    runs-on: ubuntu-latest
    name: Run Alliser
    steps:
    - uses: actions/checkout@v3
    - uses: stscoundrel/alliser-action@v0.7.2
      name: Alliser action step
      with:
        extensions: .ts,.json,.dsl
        folders: src,tests
